services:
  redis:
    image: redis:7-alpine
    container_name: rag_redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  app:
    image: 455896787118.dkr.ecr.eu-central-1.amazonaws.com/rag-app-api:latest
    container_name: rag_api

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DIALECT: mysql
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}

      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_AUTO_CONTENT_TYPE: ${AWS_S3_AUTO_CONTENT_TYPE}

      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL}
      CHAT_MODEL: ${CHAT_MODEL}
      OPENAI_COMPATIBILITY: ${OPENAI_COMPATIBILITY}

      NODE_ENV: production
      PORT: 8080
      JWT_SECRET: ${JWT_SECRET}

      REDIS_URL: ${REDIS_URL}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    ports:
      - "80:8080"

    command: >
      sh -c "npx sequelize-cli db:create && npx sequelize-cli db:migrate && npm run start"

  worker:
    image: 455896787118.dkr.ecr.eu-central-1.amazonaws.com/rag-app-worker:latest
    container_name: rag_worker
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DIALECT: mysql
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}

      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_AUTO_CONTENT_TYPE: ${AWS_S3_AUTO_CONTENT_TYPE}

      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL}
      CHAT_MODEL: ${CHAT_MODEL}
      OPENAI_COMPATIBILITY: ${OPENAI_COMPATIBILITY}

      NODE_ENV: production
      PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      WORKER_POLL_MS: 5000

      REDIS_URL: ${REDIS_URL}
    command: >
      sh -c "node dist/worker/worker.js"
    restart: unless-stopped
volumes:
  redis_data:
